version: '2'

services:
    web:
        build:
            context: .
            dockerfile: ./docker/images/lchski/nginx/Dockerfile
        image: lchski/nginx:gr-faster-api
        links:
            - php

    php:
        build:
            context: .
        links:
            - db

    db:
        image: mariadb
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=grfasterapidev
            - MYSQL_USER=grfasterapidev
            - MYSQL_PASSWORD=password

volumes:
    database:
