web:
    image: nginx
    ports:
        - "8080:80"
    volumes:
        - ./src:/srv/www
        - ./docker/conf/nginx:/etc/nginx/conf.d
    links:
        - php

php:
    image: lchski/php:7-fpm-extended
    volumes:
        - ./src:/srv/www
    links:
        - db

db:
    image: mariadb
    volumes:
        - ./docker/data/db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=grfasterapidev
        - MYSQL_USER=grfasterapidev
        - MYSQL_PASSWORD=password
